version: "3.9"

services:
  backend:
    build: ./backend
    restart: "always"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:80"
  
  frontend:
    build: ./frontend
    restart: "always"
    ports:
      - "8080:80"